name: ministry_minister_app
description: A new Flutter project.
publish_to: none

version: 1.0.12+13

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  get_storage: ^2.0.3
  loading_animations: ^2.1.0
  flutter_local_notifications: ^9.8.0+1
  change_app_package_name: ^1.1.0
  shimmer: ^2.0.0
  timeago: ^3.3.0
  convex_bottom_bar: ^3.2.0
  easy_localization: ^3.0.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  path_provider: ^2.0.12
  cached_network_image: ^3.2.1
  pull_to_refresh: ^2.0.0
  flutter_easyloading: ^3.0.5
  firebase_core: ^2.4.1
  awesome_dialog: ^2.2.0
  animated_snack_bar: ^0.2.1
  flutter_callkit_incoming: ^1.0.3+1
  wakelock: ^0.6.2
  uuid: ^3.0.7
  flutter_fcm: ^1.0.8
  firebase_messaging: ^14.2.1
  flutter_platform_widgets: ^2.0.0
  flutter_bloc: ^8.0.1
  pin_code_fields: ^7.4.0
  package_info_plus: ^1.4.2
  flutter_staggered_animations: ^1.1.1
  loading_animation_widget: ^1.2.0+4
  google_maps_flutter: ^2.2.2
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  flutter_svg: ^1.1.6
  quiver: ^3.2.1
  flutter_phoenix: ^1.0.0
  intl:
  smooth_page_indicator: ^1.0.0+2
  get_it: ^7.2.0
  pinput: ^2.2.23
  permission_handler: ^10.0.0
  share_plus: ^4.4.0
  equatable: ^2.0.5
  easy_splash_screen: ^1.0.4
  regexpattern: ^2.1.0
  flutter_screenutil: ^5.6.0
  url_launcher: ^6.1.7
  location: ^4.4.0
  dio_smart_retry: ^1.4.0
  dio_http_cache_lts: ^0.4.1
  signalr_netcore: ^1.3.2
  loader_overlay: ^2.1.0
  devicelocale: ^0.5.5
  flutter_launcher_icons: ^0.12.0
  assets_audio_player: ^3.0.6
  vibration: ^1.7.5
  agora_rtc_engine:



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_icons:
  image_path: "assets/images/ministries_logo.jpg"
  android: true
  ios: true
  adaptive_icon_foreground: "assets/images/ministries_logo.jpg"
  icon_size: 48
  web:
    generate: true
    image_path: "assets/images/ministries_logo.jpg"
    icon_size: 48
  windows:
    generate: true
    image_path: "assets/images/ministries_logo.jpg"
  macos:
    generate: true
    image_path: "assets/images/ministries_logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/locales/
    - assets/audio/


  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Black.ttf


    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/static/Outfit-Black.ttf
          weight: 900
        - asset: assets/fonts/Outfit/static/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit/static/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit/static/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit/static/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/static/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit/static/Outfit-thin.ttf
        - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit/static/Outfit-SemiBold.ttf
          weight: 900


    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf