// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN_f1rspvr5vCU76NVpyuQqaBj1svd-uw',
    appId: '1:969913072525:web:8ccd9432c22fca9c28dbc4',
    messagingSenderId: '969913072525',
    projectId: 'shva-f693f',
    authDomain: 'shva-f693f.firebaseapp.com',
    storageBucket: 'shva-f693f.appspot.com',
    measurementId: 'G-4GYH961DFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwiI0K-_hfdIrTv4wO0brJWP-AKBtsu3I',
    appId: '1:969913072525:android:203ca08ed668c79728dbc4',
    messagingSenderId: '969913072525',
    projectId: 'shva-f693f',
    storageBucket: 'shva-f693f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCKOK-_5cZUav09miC9S5Mk9-gxLTErN0',
    appId: '1:969913072525:ios:2862966345c4a1ce28dbc4',
    messagingSenderId: '969913072525',
    projectId: 'shva-f693f',
    storageBucket: 'shva-f693f.appspot.com',
    iosClientId: '969913072525-lmf2lmikhm2buntfoo2ujc9vi3frcii3.apps.googleusercontent.com',
    iosBundleId: 'com.example.shva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCKOK-_5cZUav09miC9S5Mk9-gxLTErN0',
    appId: '1:969913072525:ios:2862966345c4a1ce28dbc4',
    messagingSenderId: '969913072525',
    projectId: 'shva-f693f',
    storageBucket: 'shva-f693f.appspot.com',
    iosClientId: '969913072525-lmf2lmikhm2buntfoo2ujc9vi3frcii3.apps.googleusercontent.com',
    iosBundleId: 'com.example.shva',
  );
}
